### ISSUE TITLE
Line Break and/or Carriage Return after UUID in Clipboard Output

### ISSUE THREAD

**Issue by rclayton-the-terrible** [eliasmaier/uuidgen.alfred#1]
First of all, thank you, thank you, thank you.  I love this workflow and it's literally saved me hours of time when writing documentation (id's for JSON output when writing examples in RAML). 

I don't know if it's even possible, but is there a way to remove the line break/carriage return in the clip board content?  For instance, I'll be writing some JSON and run the workflow within a string:

```
{
    "id": "443C1C6D-8A72-4131-A6CB-7B9AB4ADF8E8
"
}
```

Which is a little annoying, but not a deal breaker.

Thanks again!

**Comment by eliasmaier** [comment]
Thank you for your feedback to my little workflow. Nice to hear that it is used by others too.

I added an option to paste a UUID without adding a newline.
Additionally I added optional hotkeys to all cases. Feel free to assign hotkeys.

I'd like to hear from you about the new version and if it fixes your issue.

**Comment by rclayton-the-terrible** [comment]
Sorry for the slow feedback.  This definitely fixes my issue.  Thanks!
